### ISSUE TITLE
Data files

### ISSUE THREAD

**Issue by iseef2** [yifding/e2e_EL_evaluate#1]
Hi
Do you have a link of datasets in the batch_dataset_a.py file
especially the wiki_hyperlink_contexts.csv file

**Comment by yifding** [comment]
Hey~
Thanks for your interest in our package and raising this question.

Basically I implemented a PyTorch version of deep-ed while the orginal version is using lua and torch.
Original package can be found at https://github.com/dalab/deep-ed, and my implementation uses exactly the same input file as theirs. I will release the package in the near future with detailed guidance.

Specifically, the **wiki_hyperlink_contexts.csv** is actually an intermediate file to obtain entity embedding by considering exsiting hyperlinks for some pre-defined set of entities. If you download the orginal data files from https://drive.google.com/uc?id=0Bx8d3azIm_ZcbHMtVmRVc1o5TWM&export=download and follow the instructions to run deep_ed_PyTorch, you should be able to get it !

I will keep you inform as soon as I polish the documentation and publicate the package.

Thank you !

**Comment by iseef2** [comment]
Thanks a lot for your reply!

**Comment by yifding** [comment]
Hello~
the package and documentation of deep_ed_PyTorch is available at https://github.com/yifding/deep_ed_PyTorch.
Please let me know if you have any questions and suggestions.
Thank you!

**Comment by iseef2** [comment]
Thanks again！
